name: hive
description: Lightweight and blazing fast key-value database written in pure Dart. Stronly encrypted using AES-256.
version: 1.2.0
authors:
  - Simon Leier <simonleier@gmail.com>
  - long1eu <lung.razvan@gmail.com>
homepage: https://github.com/long1eu/hive

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.6.4
  pointycastle: ^1.0.2
  meta: ^1.1.8

dev_dependencies:
  test: ^1.9.4
  mockito: ^4.1.1
  pedantic: ^1.9.0